version: "3.8"

services:
  mc:
    container_name: mc
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: "FABRIC"
      FABRIC_LAUNCHER_VERSION: "0.11.2"
      FABRIC_LOADER_VERSION: "0.15.3"
      VERSION: "1.20.1"
      MEMORY: "4G"
      DIFFICULTY: "hard"
      OPS: SaltySquatch04
    ports:
      - "25565:25565"
    volumes:
      - /mc_server/data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped