version: "3.8"

services:
  mc:
    container_name: mc
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: "FABRIC"
    ports:
      - "25565:25565"
    volumes:
      - /mc_server/data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped