---
version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Eastern
    volumes:
      - /media_server/appdata/config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Eastern
    volumes:
      - /media_server/appdata/config/radarr:/config
      - /media_server/media/movies:/movies 
      - /media_server/downloads:/downloads 
    ports:
      - 7878:7878
    restart: unless-stopped

---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Eastern
    volumes:
      - /media_server/appdata/config/sonarr:/config
      - /media_server/media/tv:/tv 
      - /media_server/downloads:/downloads 
    ports:
      - 8989:8989
    restart: unless-stopped

---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Eastern
      - WEBUI_PORT=8080
    volumes:
      - /media_server/appdata/config/qbittorrent:/config
      - /media_server/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

---
version: "2.1"
services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Eastern
    volumes:
      - /media_server/appdata/config/emby:/config
      - /media_server/media/tv:/data/tvshows
      - /media_server/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped

version: "3.4"
services:
  requestrr:
    image: darkalfx/requestrr
    hostname: requestrr
    container_name: requestrr
    ports:
    - 4545:4545
    volumes:
    - /media_server/appdata/config/requestrr:/root/config
    restart: unless-stopped