---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Eastern
    volumes:
      - /media_server/appdata/config/radarr:/config
      - /media_server/media/movies:/movies #optional
      - /media_server/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped