---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Eastern
    volumes:
      - /media_server/appdata/config/sonarr:/config
      - /media_server/media/tv:/tv 
      - /media_server/downloads:/downloads 
    ports:
      - 8989:8989
    restart: unless-stopped